### ISSUE TITLE
CPLVM Class Missing `fit_model_vi` method

### ISSUE THREAD

**Issue by ethanweinberger** [andrewcharlesjones/cplvm#1]
Hi Andrew. This is awesome work! Unfortunately when I tried applying it to a dataset of mine using the example in the README, I ran into an error due to the CPLVM class missing the `fit_model_vi` method

<img width="612" alt="Screen Shot 2021-11-04 at 11 10 12 AM" src="https://user-images.githubusercontent.com/7200040/140395708-1b023e7a-f173-4fa3-b9e6-6d32cae30daf.png">.

The code to reproduce the error is below:

```
from cplvm import CPLVM

foreground_data = target_adata.layers['count'].T
background_data = background_adata.layers['count'].T

model_output = cplvm.fit_model_vi(
    background_data,
    foreground_data,
    compute_size_factors=True,
    is_H0=False,
    offset_term=False
)
```

**Comment by andrewcharlesjones** [comment]
Hey Ethan, thanks for noticing this. I changed the CPLVM class so that it has the function `fit_model_vi`, so hopefully it should work now. I think the example in the README was also a bit outdated, so I updated it with the current usage. Let me know if you still run into issues.

**Comment by ethanweinberger** [comment]
Closing this since I'm no longer having this issue. Thanks for the help!
